export const projects = [
  {
    title: "Agenda Médica",
    year: 2024,
    description:
      "Plataforma de gestión de turnos con integración WhatsApp y notificaciones automáticas",
    image: "/agendatex.webp",
    demoLink: "https://agendatex.vercel.app/",
    codeLink: "https://github.com/TobiasOnandia/agendatex",
    technologies: [
      "Next.js 15",
      "Supabase",
      "TypeScript",
      "WhatsApp API",
      "Email Api",
    ],
  },
  {
    title: "Odisea indumentaria",
    year: 2024,
    description:
      "E-commerce con integración de Mercado Pago, WhatsApp ,sistema de notificaciones y panel de administracion",
    image: "/odisea.webp",
    demoLink: "https://odiseaof.com/",
    technologies: [
      "Next.js 15",
      "Supabase",
      "Mercado Pago",
      "Email Api",
      "WhatsApp API",
      "Tailwind CSS",
      "TypeScript",
    ],
  },
  {
    title: "Axis Team",
    year: 2024,
    description:
      "Landing page corporativa con rendimiento optimizado y SEO avanzado",
    image: "/axis.webp",
    demoLink: "https://www.equipoaxis.com.ar",
    technologies: ["Astro", "Tailwind CSS", "TypeScript"],
  },
  {
    title: "Nrx",
    year: 2025,
    description:
      "Desarrollado como un proyecto **full-stack**, Nrx exhibe una arquitectura robusta para la **creación y gestión de dashboards dinámicos**. Destaca por su diseño de componentes modular, manejo eficiente de datos y uso de **Server Actions** para una interacción fluida con el backend, demostrando sólidas prácticas de desarrollo web moderno.",
    image: "/nrx.png",
    demoLink: "https://nrx-rgmu.vercel.app/",
    codeLink: "https://github.com/TobiasOnandia/nrx.git",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "React Query",
      "Prisma",
      "PostgreSQL",
      "NextAuth.js",
      "Server Actions",
      "Shadcn UI",
      "React Grid Layout",
      "Chart.js",
    ],
  },
  {
    title: "Blog",
    year: 2025,
    description: "Blog personal con integración de Supabase, Prisma y tRPC",
    image: "/blog.png",
    demoLink: "https://blog-xi-ten-88.vercel.app",
    codeLink: "https://github.com/TobiasOnandia/blog",
    technologies: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "Prisma",
      "PostgreSQL",
      "Supabase",
      "tRPC",
    ],
  },
];
